"fix: create-release"

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -3,11 +3,11 @@ name: Create Meta Release
 on:
   push:
     tags:
-      - 'v*.*.*'
+      - "v*.*.*"
   workflow_dispatch:
     inputs:
       release_tag:
-        description: 'vx.y.z'
+        description: "vx.y.z"
         required: true
         type: string
 
@@ -21,9 +21,13 @@ jobs:
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
-          distribution: 'zulu'
-          java-version: '17'
-          cache: 'gradle'
+          distribution: "zulu"
+          java-version: "17"
+          cache: "gradle"
+      - name: Grant execute permissions for gradle
+        run: chmod +x gradlew
+      - name: Run unit tests
+        run: ./gradlew clean testDebug
 
       - name: Build APK
         run: |
@@ -44,26 +48,30 @@ jobs:
         run: |
           BUILD_TOOLS_DIR=$(ls -d $ANDROID_HOME/build-tools/*/ | sort -V | tail -n 1)
           if [ -z "$BUILD_TOOLS_DIR" ]; then
-            echo "No build-tools found in $ANDROID_HOME/build-tools"
+            echo "No build-tools found"
             exit 1
           fi
+
           APKSIGNER="${BUILD_TOOLS_DIR}apksigner"
           if [ ! -f "$APKSIGNER" ]; then
-            echo "apksigner not found at $APKSIGNER"
+            echo "apksigner not found"
             exit 1
           fi
-          if [ ! -f app/build/outputs/apk/release/app-release-unsigned.apk ]; then
-            echo "APK not found at app/build/outputs/apk/release/app-release-unsigned.apk"
-            exit 1
-          fi
-          $APKSIGNER sign \
-            --ks $RUNNER_TEMP/keystores/keystore.jks \
-            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
-            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
-            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
-            --out app-release.apk \
-            app/build/outputs/apk/release/app-release-unsigned.apk
 
+          if [ ! -f app/build/outputs/apk/release/app-release-unsigned.apk ]; then
+            echo "APK not found"
+            exit 1
+          fi
+
+          cp app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk
+
+          $APKSIGNER sign \
+            --ks "$RUNNER_TEMP/keystores/keystore.jks" \
+            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
+            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
+            --key-pass pass:${{ secrets.KEY_PASSWORD }}" \
+            app-release.apk
+            
       - name: Clean Up Keystore
         if: always()
         run: |
